package za.ac.cput.domain;

import jakarta.persistence.*;
import za.ac.cput.domain.security.User;

import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

@Entity
public class Booking {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
    @Column(nullable = false, unique = true, updatable = false)
    private UUID uuid;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    @ManyToOne
    @JoinColumn(name = "car_id")
    private Car car;

 /*   @ManyToOne
    @JoinColumn(name = "driver_id")
    private Driver driver;*/

    private LocalDateTime bookingStartDate;
    private LocalDateTime bookingEndDate;
    private String status; // PENDING, CONFIRMED, CANCELED
    private boolean deleted = false;
    @PrePersist
    protected  void onCreate() {
        if (this.uuid == null) {
            this.uuid = UUID.randomUUID();
            System.out.println("UUID generated by booking entity: " + this.uuid);
        }
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }



    // Constructors

    public Booking() {
    }

    public Booking(Builder builder) {
        this.id = builder.id;
        this.uuid = builder.uuid;
        this.user = builder.user;
        this.car = builder.car;
//this.driver = builder.driver;
        this.bookingStartDate = builder.bookingDate;
        this.bookingEndDate = builder.returnedDate;
        this.status = builder.status;

    }

    // Getters

    public int getId() {
        return this.id;
    }
    public UUID getUuid() {
        return this.uuid;
    }

    public User getUser() {
        return user;
    }

    public Car getCar() {
        return car;
    }

//    public Driver getDriver() {
//        return driver;
//    }

    public LocalDateTime getBookingStartDate() {
        return bookingStartDate;
    }

    public LocalDateTime getBookingEndDate() {
        return bookingEndDate;
    }

    // Setters

    public void setId(int id) {
        this.id = id;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public void setCar(Car car) {
        this.car = car;
    }

//    public void setDriver(Driver driver) {
//        this.driver = driver;
//    }

    public void setBookingStartDate(LocalDateTime bookingDate) {
        this.bookingStartDate = bookingDate;
    }

    public void setBookingEndDate(LocalDateTime returnedDate) {
        this.bookingEndDate = returnedDate;
    }
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    public boolean isDeleted() {
        return deleted;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Booking booking = (Booking) o;
        return id == booking.id && deleted == booking.deleted && Objects.equals(uuid, booking.uuid) && Objects.equals(user, booking.user) && Objects.equals(car, booking.car) && Objects.equals(bookingStartDate, booking.bookingStartDate) && Objects.equals(bookingEndDate, booking.bookingEndDate) && Objects.equals(status, booking.status);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, uuid, user, car, bookingStartDate, bookingEndDate, status, deleted);
    }

    @Override
    public String toString() {
        return "Booking{" +
                "id=" + id +
                ", uuid=" + uuid +
                ", user=" + user +
                ", car=" + car +
                ", bookingStartDate=" + bookingStartDate +
                ", bookingEndDate=" + bookingEndDate +
                ", status='" + status + '\'' +
                ", deleted=" + deleted +
                '}';
    }
// Builder pattern

    public static class Builder {
        private int id;
        private UUID uuid ;
        private User user;
        private Car car;
        //        private Driver driver;
        private LocalDateTime bookingDate;
        private LocalDateTime returnedDate;
        private String status;
        private boolean deleted;

        public Builder id(int id) {
            this.id = id;
            return this;
        }
        public Builder uuid(UUID uuid) {
            this.uuid = uuid;
            return this;
        }

        public Builder user(User user) {
            this.user = user;
            return this;
        }

        public Builder car(Car car) {
            this.car = car;
            return this;
        }
//
//        public Builder driver(Driver driver) {

        /// /            this.driver = driver;
//            return this;
//        }
        public Builder bookingDate(LocalDateTime bookingDate) {
            this.bookingDate = bookingDate;
            return this;
        }

        public Builder returnedDate(LocalDateTime returnedDate) {
            this.returnedDate = returnedDate;
            return this;
        }

        public Builder status(String status) {
            this.status = status;
            return this;
        }
        public Builder deleted(boolean deleted) {
            this.deleted = deleted;
            return this;
        }

        public Builder copy(Booking booking) {
            this.id = booking.id;
            this.user = booking.user;
            this.car = booking.car;
//          this.driver = booking.driver;
            this.bookingDate = booking.bookingStartDate;
            this.returnedDate = booking.bookingEndDate;
            this.status = booking.status;
            this.deleted = booking.deleted;
            return this;
        }
        public Booking build() {
            return new Booking(this);
        }

    }
}
