apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # URL points to the Prometheus service within the Docker network
    url: http://prometheus:9090
    isDefault: true