version: '3.8'

services:

  app:
    image: nemesisguy/on-the-go-rentals-backend:latest
    container_name: on-the-go-rentals-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3307/OnTheGoRentalsDatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my_secret_passwords
    ports:
      - "8080:8080"

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
